title: Crypto Static (Rate) Free API Rate
description: Free API Rate and Ticker For Hit and Top cryptocurrencies
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

github:
  zip_url: https://github.com/Crypto-Static/Rate/blob/main/rateStatic.json
  another_url: https://github.com/Crypto-Static/Rate/raw/main/rateStatic.json

incremental: false
highlighter: rouge

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

keywords: 
  - rate
  - cryptocurrency
  - ticker
  - wallet
  - range
  - rate bitcoin
  - rate ethereum
  - rate tron
  - rate dogecoin
  - rate dash
  - rate zcash
  - rate litecoin
  - rate cardano
  - free api
  - free rate api

# Where things are
source: _docs
destination: _docs/_site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes


# Outputting
permalink: /:title.html
paginate_path: /page:num
timezone: null

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Markdown Processors
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
